# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
# env: 
#   action_state: anything
env:
    BUCKET_BASE_URL: https://festatic.adev.scopely.io
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - run: echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
    - name: Print vars
      run: echo "${{ steps.slug.outputs.sha7 }}"
    - run: echo "action_state=yellow" >> $GITHUB_ENV
    - run: echo "${{ github.event.repository.name }}"
    - run: echo "${{ env.action_state }} ${{ env.short_sha }} ${{ env.REPO_NAME }} ${{ github.event.repository.id }}"
  
    - name: Slack Notification
      uses: 8398a7/action-slack@v3
      with:
        status: custom
        channel: C01DNDMS3ND
        custom_payload: |
            {
              text: "Custom Field Check",
              attachments: [{
                "author_name": "8398a7@action-slack", // json
                fallback: 'fallback',
                color: 'good',
                title: 'CI Result',
                text: 'Succeeded',
                fields: [{
                  title: 'lower case',
                  value: 'LOWER CASE CHECK'.toLowerCase(),
                  short: true
                },
                {
                  title: 'reverse',
                  value: 'gnirts esrever'.split('').reverse().join(''),
                  short: true
                },
                {
                  title: 'long title1',
                  value: 'long value1',
                  short: false
                }],
                actions: [{
                }]
              }]
            }
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.PORTAL_CI_CD_SLACK_WEBHOOK }} # required
           
