# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
# env: 
#   action_state: anything
env:
    BUCKET_BASE_URL: https://festatic.adev.scopely.io
    REPO_NAME: ${{ github.event.repository.name }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - run: echo "short_sha=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_ENV
    - name: Print vars
      run: echo "${{ steps.slug.outputs.sha7 }}"
    - run: echo "action_state=yellow" >> $GITHUB_ENV
    - run: echo "${{ github.event.repository.name }}"
    - run: echo "${{ env.action_state }} ${{ env.short_sha }} ${{ env.REPO_NAME }} ${{ github.event.repository.id }}"
  
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@master
      env:
          SITE_NAME: portal.adev.scopely.io 
          SLACK_USERNAME: Portal_CI
          SLACK_CHANNEL: portal-testing
          SLACK_ICON_EMOJI: ':zap:'
          SLACK_FOOTER: Powered by portal team
          SLACK_TITLE: Default theme testing Url
          SLACK_WEBHOOK: ${{ secrets.PORTAL_CI_CD_SLACK_WEBHOOK }}
          MSG_MINIMAL: true
          SLACK_MESSAGE: '{"text":"Custom payload from {{ GITHUB_REPOSITORY }} \\n *with* `new` _line_ escaped","username": "{{ GITHUB_ACTOR }}"}'

           
