# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep for 30 m
      uses: jakejarvis/wait-action@master
      with:
        time: '30m'
