on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        default: '["portalHost","portalCommon"]'
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ${{ github.event.inputs.tags }}
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - run: echo "I am here"
    
# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Run a one-line script
#       run: |
#         echo "Tags: ${{ github.event.inputs.tags }} ${{ github.event.inputs.tags }}[0]"
#     - run: for f in ${{ github.event.inputs.tags }}; do echo $f; done

