# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Print vars
      run: echo "${{ env.GITHUB_SHA_SHORT }}"
    - run: echo "${{ env.GITHUB_SHA }}"
