on: 
  workflow_dispatch:
    inputs:
      portalHost:
        description: 'Portal Host'     
        required: true
        default: 'beta'
      portalStarter:
        description: 'Portal Starter'     
        required: true
        default: 'beta'
      portalCommon:
        description: 'Portal Common'     
        required: true
        default: 'beta'
jobs:
  get-shared:
    runs-on: ubuntu-latest
    steps:
      - uses: isawalhi/applitools_hackathon_2020/shared@v1
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: ["${{ github.event.inputs.portalHost }}","${{ github.event.inputs.portalStarter }}"]
    steps:
      - run: echo "test"
  deploy:
     needs: build
     runs-on: ubuntu-latest
     steps:
       - run: echo "I am here ${{ github.event.inputs }}"
    
# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Run a one-line script
#       run: |
#         echo "Tags: ${{ github.event.inputs.tags }} ${{ github.event.inputs.tags }}[0]"
#     - run: for f in ${{ github.event.inputs.tags }}; do echo $f; done

