# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Get short SHA
      id: slug
      run: echo "::set-output name=sha7::$(echo ${GITHUB_SHA} | cut -c1-7)"
    - name: Print vars
      run: echo "${{ steps.slug.outputs.sha7 }}"
    - run: echo "${{ steps.today.outputs.date }}"
    - run: echo "${{ github.event.repository.name }}"
