on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'
        default: '[{"portalHost":"beta"},{"portalCommon":"master"}]'
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a one-line script
      run: |
        echo "Tags: ${{ github.event.inputs.tags }} ${{ github.event.inputs.tags }}[0]" 

