name: Octo Organization CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      run: git clone https://github.com/isawalhi/applitools_hackathon_2020.git portal-new
      run:|
          cd portal-new
          git checkout master
